baseUrl: '@web/cordova-public-market'
enabled: true
handle: cordovaPublicMarket
hasUrls: true
language: en-PH
name: 'Cordova Public Market'
primary: false
siteGroup: 24b75201-290a-4426-a670-88ee49d5d4c1
sortOrder: 15
