baseUrl: '@web/koop-meat-factory'
enabled: true
handle: koopMeatFactory
hasUrls: true
language: en-PH
name: 'Koop Meat Factory'
primary: false
siteGroup: 24b75201-290a-4426-a670-88ee49d5d4c1
sortOrder: 8
