baseUrl: '@web/roosekie-pharmacy'
enabled: true
handle: roosekiePharmacy
hasUrls: true
language: en-PH
name: 'Roosekie Pharmacy'
primary: false
siteGroup: 24b75201-290a-4426-a670-88ee49d5d4c1
sortOrder: 3
