baseUrl: '@web/y-and-c-marketing'
enabled: true
handle: yAndCMarketing
hasUrls: true
language: en-PH
name: 'Y and C Marketing'
primary: false
siteGroup: 24b75201-290a-4426-a670-88ee49d5d4c1
sortOrder: 11
