contentColumnType: string(7)
fieldGroup: bdf930d1-a02d-4fe0-a691-afde504fc428
handle: color
instructions: ''
name: Color
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
