contentColumnType: string
fieldGroup: 3de17496-4f79-4698-9690-1f884df149eb
handle: superFilterReleaseDate
instructions: ''
name: 'Release Date'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '2011'
        -
          - value
          - '2011'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2012'
        -
          - value
          - '2012'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2013'
        -
          - value
          - '2013'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2014'
        -
          - value
          - '2014'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2015'
        -
          - value
          - '2015'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2016'
        -
          - value
          - '2016'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2017'
        -
          - value
          - '2017'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2018'
        -
          - value
          - '2018'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2019'
        -
          - value
          - '2019'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2020'
        -
          - value
          - '2020'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2021'
        -
          - value
          - '2021'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2022'
        -
          - value
          - '2022'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2023'
        -
          - value
          - '2023'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2024'
        -
          - value
          - '2024'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2025'
        -
          - value
          - '2025'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
