contentColumnType: string
fieldGroup: 3de17496-4f79-4698-9690-1f884df149eb
handle: superFilterShowTypes
instructions: ''
name: 'Show Types'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Films
        -
          - value
          - films
        -
          - default
          - ''
    -
      __assoc__:
        -
          - optgroup
          - Series
    -
      __assoc__:
        -
          - label
          - 'TV Series'
        -
          - value
          - tv-series
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Documentaries
        -
          - value
          - documentaries
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Anime
        -
          - value
          - anime
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
