description: ''
handle: mamalit
name: Mamalit
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-commerce
  - accessplugin-super-filter
  - accesssitewhensystemisoff
  - administrateusers
  - assignusergroups
  - assignuserpermissions
  - commerce-capturepayment
  - commerce-deleteorders
  - commerce-editorders
  - commerce-managecustomers
  - commerce-manageorders
  - commerce-manageproducts
  - 'commerce-manageproducttype:94ba3c16-b6df-48c5-b054-67ccaffca78a'
  - 'commerce-manageproducttype:fe07a1cf-dc3e-451c-bccf-2803b4b95d42'
  - commerce-managepromotions
  - commerce-manageshipping
  - commerce-managestoresettings
  - commerce-managesubscriptions
  - commerce-managetaxes
  - commerce-refundpayment
  - 'createentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'createfoldersinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - customizesources
  - 'deleteentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'deletefilesandfoldersinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'deletepeerentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'deletepeerentrydrafts:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'deletepeerentrydrafts:b5855906-c4ab-4ba3-99b2-fd7a2657441b'
  - 'deletepeerfilesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - deleteusers
  - 'editcategories:97340356-e9fd-4bef-a206-56fa044fa765'
  - 'editentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'editentries:b5855906-c4ab-4ba3-99b2-fd7a2657441b'
  - 'editglobalset:8469253e-519e-4657-a3f6-e1797fb6f6b5'
  - 'editimagesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'editpeerentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'editpeerentrydrafts:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'editpeerentrydrafts:b5855906-c4ab-4ba3-99b2-fd7a2657441b'
  - 'editpeerfilesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'editpeerimagesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'editsite:2660bd5c-1f43-4885-8337-ab29818b7dd5'
  - 'editsite:36c91ae9-5910-4c1a-9a8f-5d954b1ab6f9'
  - 'editsite:62a401cd-ff6e-4f67-8095-54df23406a9c'
  - 'editsite:7d4f742d-99a6-4087-a186-b767375ff31c'
  - 'editsite:97afb406-be52-4152-8b2e-3322f7197477'
  - 'editsite:a70c5f96-9fc5-46c4-a4ad-0b87be905c18'
  - 'editsite:cb9c61ec-ed8a-416e-aaab-80285bab6886'
  - editusers
  - impersonateusers
  - moderateusers
  - performupdates
  - 'publishentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'publishentries:b5855906-c4ab-4ba3-99b2-fd7a2657441b'
  - 'publishpeerentries:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'publishpeerentrydrafts:83e45ca0-4804-49d6-8329-294ba7492ad2'
  - 'publishpeerentrydrafts:b5855906-c4ab-4ba3-99b2-fd7a2657441b'
  - registerusers
  - 'replacefilesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'replacepeerfilesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'saveassetinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewpeerfilesinvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
  - 'viewvolume:ec975d9e-0a9e-4068-9eaf-bcf9cd0d52dc'
