enableVersioning: true
handle: superFilterShows
name: Shows
propagationMethod: all
siteSettings:
  2660bd5c-1f43-4885-8337-ab29818b7dd5:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  36c91ae9-5910-4c1a-9a8f-5d954b1ab6f9:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  62a401cd-ff6e-4f67-8095-54df23406a9c:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  7d4f742d-99a6-4087-a186-b767375ff31c:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  97afb406-be52-4152-8b2e-3322f7197477:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  cb9c61ec-ed8a-416e-aaab-80285bab6886:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
  e293e18c-9b24-4098-a340-b136cfb50199:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'super-filter-shows/{slug}'
type: channel
